services:
  product-service:
    build: ./product-service
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=3001
    networks:
      - sales-network

  order-service:
    build: ./order-service
    ports:
      - "3002:3002"
    depends_on:
      - mongodb
      - rabbitmq
    environment:
      - PORT=3002
    networks:
      - sales-network

  customer-service:
    build: ./customer-service
    ports:
      - "3003:3003"
    depends_on:
      - mongodb
    environment:
      - PORT=3003
    networks:
      - sales-network

  api-gateway:
    build: ./api-gateway
    ports:
      - "3000:3000"
    depends_on:
      - product-service
      - order-service
      - customer-service
    networks:
      - sales-network

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - sales-network

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - sales-network

volumes:
  mongo-data:

networks:
  sales-network:
    driver: bridge